sudo: false

language: php

php:
    - 7.0
    - 7.1
    - 7.2
    - 7.3

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master
    - develop

cache:
  apt: true
  directories:
    - node_modules
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:
    - php: 7.3
      env: WP_VERSION=latest WP_MULTISITE=0
    - php: 7.2
      env: WP_VERSION=latest WP_MULTISITE=0
    - php: 7.2
      env: WP_VERSION=latest WP_MULTISITE=1
    - php: 7.1
      env: WP_VERSION=latest WP_MULTISITE=0
    - php: 7.0
      env: WP_VERSION=latest WP_MULTISITE=1

install:
  # Speed up build time by disabling Xdebug.
  # https://johnblackbourn.com/reducing-travis-ci-build-times-for-wordpress-projects/
  # https://twitter.com/kelunik/status/954242454676475904
  - phpenv config-rm xdebug.ini || echo 'No xdebug config.'
  # Install PHP CodeSniffer.
  - composer install --no-interaction --no-suggest
  - phpenv rehash

script:
  # Search for PHP syntax errors.
  - find -L . -path ./vendor -prune -o -name '*.php' -print0 | xargs -0 -n 1 -P 4 php -l
  # Run PHPCS.
  - composer check-cs -- --runtime-set ignore_warnings_on_exit 1
